### ISSUE TITLE
Invalid conversion factors

### ISSUE THREAD

**Issue by cmutel** [sc-gcoste/brightway-agribalyse3.1#3]
@sc-gcoste 

The conversion factors in the [import notebook](https://github.com/sc-gcoste/brightway-agribalyse3.1/blob/master/build_agb3.1_database.ipynb) in the migration `agb_technosphere_migration_data` are wrong. For example, converting litres to cubic meters is a factor of one thousand, but `10E-3` is only a factor of 100:

```python
In [1]: 10E-3
Out[1]: 0.01
```

**Comment by sc-gcoste** [comment]
Wow, nice one! Thanks @cmutel, I'll fix this.
