### ISSUE TITLE
Invalid exchange

### ISSUE THREAD

**Issue by GreLeBr** [sc-gcoste/brightway-agribalyse3.1#4]
I can load the database but I am running into a similar error no matter the VM I am using:  
Exchange between ('biosphere3', '9c2a7dc9-8b1f-46ba-bc16-0d761a4f6016') and ('agribalyse3.1', '000e9244de28ae395da776d83745d6ff') is invalid - one of these objects is unknown (i.e. doesn't exist as a process dataset)  

is it an issue on my end or a known issue. 
I am using the ademe link for agribalyse 3.1

**Comment by sc-gcoste** [comment]
Hi, is there a `biosphere3` database set up in your project? If no, first do `bw.bw2setup()`.

**Comment by GreLeBr** [comment]
Yes there is a biosphere setup.

**Comment by cyrillefrancois** [comment]
Same issue with the BW2PACKAGE file from opendata.ademe.fr. The version on this site is not updated, because the agribalyse biosphere only contains 1883 additional supplementary flows. In parallele I did the import from SIMAPRO file, and the agribalyse biosphere contains 2208 elementary flows.

**Comment by tngTUDOR** [comment]
bitten by the same error here. I guess this is an issue with the exact version of the bw2 biosphere db being used. I'll try to track down the offending biosphere3 flow (9c2a7dc9-8b1f-46ba-bc16-0d761a4f6016).

**Comment by tngTUDOR** [comment]
I seems that the offending flow is:

```python3
In [5]: bio_db.get('9c2a7dc9-8b1f-46ba-bc16-0d761a4f6016')
Out[5]: 'Ethene' (kilogram, None, ('air',))
```

**Comment by tngTUDOR** [comment]
> I seems that the offending flow is:
> 
> ```python
> In [5]: bio_db.get('9c2a7dc9-8b1f-46ba-bc16-0d761a4f6016')
> Out[5]: 'Ethene' (kilogram, None, ('air',))
> ```

I found this out by using the bw2io version 0.8.7, because the agribalyse database is linked to ecoinvent 3.8. The bw2io documentation states that a bw2 installation that is compatible with ecoinvent 3.8 needs version 0.8.7.

**Comment by tngTUDOR** [comment]
I can confirm that if you create an environment with bw2io = 0.8.7, the import of the bw2 package found in this repo works flawlessly:

```
In [3]: bi.bw2setup()
Creating default biosphere

Applying strategy: normalize_units
Applying strategy: drop_unspecified_subcategories
Applying strategy: ensure_categories_are_tuples
Applied 3 strategies in 0.00 seconds
Writing activities to SQLite3 database:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00
Title: Writing activities to SQLite3 database:
Started: 10/15/2023 14:39:04
Finished: 10/15/2023 14:39:04
Total time elapsed: 00:00:00
CPU %: 97.80
Memory %: 0.39
Created database: biosphere3
Creating default LCIA methods

Applying strategy: normalize_units
Applying strategy: set_biosphere_type
Applying strategy: fix_ecoinvent_38_lcia_implementation
Applying strategy: drop_unspecified_subcategories
Applying strategy: link_iterable_by_fields
Applied 5 strategies in 0.55 seconds
Wrote 975 LCIA methods with 254388 characterization factors
Creating core data migrations

```

```
In [4]: bio_db = bd.Database('biosphere3')

In [5]: bio_db.get('9c2a7dc9-8b1f-46ba-bc16-0d761a4f6016')
Out[5]: 'Ethene' (kilogram, None, ('air',))

In [6]: bi.BW2Package.import_file('AGB31.bw2package')
Writing activities to SQLite3 database:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00
Title: Writing activities to SQLite3 database:
Started: 10/15/2023 14:43:38
Finished: 10/15/2023 14:43:38
Total time elapsed: 00:00:00
CPU %: 96.10
Memory %: 32.65
Writing activities to SQLite3 database:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:01:35
Title: Writing activities to SQLite3 database:
Started: 10/15/2023 14:43:40
Finished: 10/15/2023 14:45:16
Total time elapsed: 00:01:35
CPU %: 99.80
Memory %: 32.65
Out[6]:
[Brightway2 SQLiteBackend: agribalyse3.1 biosphere flows,
Brightway2 SQLiteBackend: agribalyse3.1]

In [7]: bd.databases
Out[7]:
Databases dictionary with 3 object(s):
agribalyse3.1
agribalyse3.1 biosphere flows
biosphere3

```

**Comment by tngTUDOR** [comment]
so, @sc-gcoste , I think that you could "close" this issue, by specifying that one needs to have version 0.8.7 of bw2io to be able to import the bw2package ademe has to offer ;)

**Comment by sc-gcoste** [comment]
Thanks for the investigation @tngTUDOR
